name: CRON
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - run: bash /github/workspace/src/cron_data.sh
      - uses: actions/upload-artifact@v2
        with:
          name: outages
          path: *.jsonl
